name: screen_brightness_macos
description: The macOS federated plugin implementation of the screen_brightness.
version: 1.0.0
homepage: https://github.com/aaassseee/screen_brightness
repository: https://github.com/aaassseee/screen_brightness/tree/master/screen_brightness_macos
issue_tracker: https://github.com/aaassseee/screen_brightness/issues

topics:
  - screen
  - monitor
  - brightness

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  screen_brightness_platform_interface: ">=1.0.0 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=3.0.0 <4.0.0"

#dependency_overrides:
#  screen_brightness_platform_interface:
#    path: ../screen_brightness_platform_interface/

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: ScreenBrightnessMacosPlugin
